[package]
name = "liquid-staking-abi"
version = "0.0.0"
authors = ["Sorin Petreasca <sorin.petreasca@multiversx.com>"]
edition = "2021"
publish = false
[dependencies.liquid-staking]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.48.0"
