[package]
name = "gravity-restaking-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.gravity-restaking]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.48.0"
default-features = false
